xalvarez/ansible-ubuntu-setup

- roles/common/tasks/apt.yml
Solves https://github.com/xalvarez/ansible-ubuntu-setup/issues/13
> Add git official repository

- roles/dev/tasks/main.yml
- roles/dev/tasks/nodejs.yml
Solves https://github.com/xalvarez/ansible-ubuntu-setup/issues/10
> Install Node.js and npm

- roles/work/tasks/aws_vault.yml
- roles/work/tasks/main.yml
- roles/work/vars/main.yml
Solves https://github.com/xalvarez/ansible-ubuntu-setup/issues/12
> Upgrade aws-vault

- .github/workflows/main.yml
- roles/common/tasks/apt.yml
- roles/common/tasks/flatpak.yml
- roles/dev/tasks/bash_git_prompt.yml
- roles/dev/tasks/docker.yml
- roles/dev/tasks/flatpak.yml
- roles/entertainment/tasks/flatpak.yml
- roles/gnome/tasks/gsettings.yml
- roles/work/tasks/teams.yml
Resolves https://github.com/xalvarez/ansible-ubuntu-setup/issues/29
> Add GitHub Actions workflow

- roles/work/tasks/snap.yml
Resolves https://github.com/xalvarez/ansible-ubuntu-setup/issues/31
> Install 'go'

- roles/gnome/tasks/dash_to_dock.yml
- roles/gnome/tasks/dconf.yml
- roles/gnome/tasks/main.yml
Resolves https://github.com/xalvarez/ansible-ubuntu-setup/issues/38
> Set up 'Dash to Dock'

- roles/work/tasks/apt.yml
Resolves https://github.com/xalvarez/ansible-ubuntu-setup/issues/48
> Install jq

- roles/work/tasks/snap.yml
Resolves https://github.com/xalvarez/ansible-ubuntu-setup/issues/49
> Install 'yq'

- roles/work/tasks/apt.yml
Resolves https://github.com/xalvarez/ansible-ubuntu-setup/issues/50
> Install missing samba dependencies

- roles/work/tasks/aws_session_manager_plugin.yml
- roles/work/tasks/main.yml
Resolves https://github.com/xalvarez/ansible-ubuntu-setup/issues/46
> Install AWS Session Manager Plugin

- roles/common/tasks/main.yml
- roles/common/tasks/standard_notes.yml
- roles/common/vars/main.yml
Resolves https://github.com/xalvarez/ansible-ubuntu-setup/issues/47
> Download 'Standard Notes'

- roles/gnome/tasks/dconf.yml
Resolves: https://github.com/xalvarez/ansible-ubuntu-setup/issues/53
> Use 4 workspaces spanning across all monitors

- roles/gnome/tasks/dconf.yml
Resolves https://github.com/xalvarez/ansible-ubuntu-setup/issues/52
> Set workspace related keyboard shortcuts

- roles/common/tasks/apt.yml
- roles/common/vars/main.yml
- roles/dev/vars/main.yml
- roles/work/vars/main.yml
Resolves https://github.com/xalvarez/ansible-ubuntu-setup/issues/64
> Upgrade multiple packages

- roles/work/tasks/apt.yml
maven wrapper should be used instead
> Do not install maven

- roles/work/tasks/apt.yml
Resolves https://github.com/xalvarez/ansible-ubuntu-setup/issues/71
> Stop installing specific python version

- roles/work/tasks/apt.yml
- roles/work/tasks/flatpak.yml
Resolves https://github.com/xalvarez/ansible-ubuntu-setup/issues/82
> Install Zoom from .deb

- roles/work/tasks/apt.yml
- roles/work/tasks/snap.yml
Resolves https://github.com/xalvarez/ansible-ubuntu-setup/issues/88
> Install latest aws-cli

- roles/work/tasks/main.yml
- roles/work/tasks/saml2aws.yml
- roles/work/vars/main.yml
Resolves https://github.com/xalvarez/ansible-ubuntu-setup/issues/84
> Install saml2aws

- roles/work/tasks/aws_nuke.yml
- roles/work/tasks/main.yml
- roles/work/vars/main.yml
Resolves https://github.com/xalvarez/ansible-ubuntu-setup/issues/87
> Install aws-nuke

- roles/work/tasks/terraform.yml
- roles/work/vars/main.yml
Resolves https://github.com/xalvarez/ansible-ubuntu-setup/issues/90
> Install terraform 0.11.x and terraform 0.12.x

- roles/common/tasks/apt.yml
For now I'm happy with Ubuntu's default git package
> Remove git ppa

- roles/common/tasks/apt.yml
- roles/dev/tasks/apt.yml
- roles/dev/tasks/main.yml
- roles/work/vars/main.yml
Resolves https://github.com/xalvarez/ansible-ubuntu-setup/issues/96
> Install openjdk 14

- roles/dev/tasks/docker.yml
Fixes https://github.com/xalvarez/ansible-ubuntu-setup/issues/123
> Enable docker service

- roles/gnome/tasks/dconf.yml
Resolves https://github.com/xalvarez/ansible-ubuntu-setup/issues/122
> Show week numbers on calendar

- roles/work/vars/main.yml
Resolves https://github.com/xalvarez/ansible-ubuntu-setup/issues/127
> Upgrade terraform

- roles/gnome/tasks/apt.yml
- roles/gnome/tasks/dconf.yml
Resolves https://github.com/xalvarez/ansible-ubuntu-setup/issues/126
> Install system monitor

- roles/dev/tasks/sdkman.yml
- roles/dev/vars/main.yml
- roles/work/tasks/sdkman.yml
- roles/work/vars/main.yml
Resolves https://github.com/xalvarez/ansible-ubuntu-setup/issues/136
> Remove micronaut and update all package versions

- roles/work/tasks/main.yml
- roles/work/tasks/terraform.yml
- roles/work/tasks/terraform11.yml
- roles/work/tasks/terraform12.yml
- roles/work/tasks/terraform13.yml
- roles/work/vars/main.yml
Resolves https://github.com/xalvarez/ansible-ubuntu-setup/issues/135
> Install terraform 13

- .github/workflows/main.yml
- roles/dev/tasks/sdkman.yml
- roles/dev/vars/main.yml
- roles/work/tasks/sdkman.yml
- roles/work/vars/main.yml
Resolves https://github.com/xalvarez/ansible-ubuntu-setup/issues/140
> Remove JDK 8

- roles/common/tasks/snap.yml
Resolves https://github.com/xalvarez/ansible-ubuntu-setup/issues/143
> Use shutter instead of ksnip

- pre_tasks.yml
- roles/asdf/tasks/java.yml
- roles/asdf/tasks/main.yml
- roles/dev/tasks/bash_git_prompt.yml
- roles/dev/tasks/main.yml
- roles/dev/vars/main.yml
Reverts xalvarez/ansible-ubuntu-setup#168
> Revert "Reorganize asdf tasks"

- README.md
- roles/common/tasks/asdf.yml
- roles/home/tasks/asdf.yml
- roles/work/tasks/asdf.yml
Resolves https://github.com/xalvarez/ansible-ubuntu-setup/issues/167
> Install Node.js 12 and 14

- roles/work/tasks/aws.yml
Resolves https://github.com/xalvarez/ansible-ubuntu-setup/issues/172
> Install aws cli v2

- roles/common/tasks/apt.yml
- roles/common/tasks/docker.yml
- roles/common/vars/main.yml
Resolves https://github.com/xalvarez/ansible-ubuntu-setup/issues/194
> Install docker-compose v2

- playbook.yml
- pre_tasks.yml
- roles/common/tasks/apt.yml
- roles/common/tasks/flatpak.yml
- roles/common/tasks/main.yml
- roles/common/tasks/snap.yml
- roles/entertainment/tasks/flatpak.yml
- roles/entertainment/tasks/main.yml
- roles/work/tasks/flatpak.yml
- roles/work/tasks/main.yml
Resolves https://github.com/xalvarez/ansible-ubuntu-setup/issues/187 and resolves https://github.com/xalvarez/ansible-ubuntu-setup/issues/188
> Remove flatpak

- roles/work/tasks/github_cli.yml
- roles/work/tasks/main.yml
Resolves https://github.com/xalvarez/ansible-ubuntu-setup/issues/181
> Install GitHub CLI using apt

- roles/common/tasks/apt.yml
- roles/work/tasks/apt.yml
Resolves https://github.com/xalvarez/ansible-ubuntu-setup/issues/184
> Install pipx

- roles/common/files/fish_user_key_bindings.fish
- roles/common/tasks/fish.yml
Resolves https://github.com/xalvarez/ansible-ubuntu-setup/issues/148
> Add fish fzf key bindings

- roles/work/tasks/main.yml
- roles/work/tasks/npm.yml
Resolves https://github.com/xalvarez/ansible-ubuntu-setup/issues/203
> Install fx
